# Numpy
NumPy (oder Numpy) ist eine Lineare Algebra Library für Python. Dass sie so wichtig für Data Science mit Python ist, liegt daran, dass fast alle Libraries im PyData Ökosystem auf NumPy zurückgreifen.
NumPy ist außerdem extrem schnell, da es Anbindung an die C Library hat. Für mehr Informationen darüber, warum man Arrays statt Listen verwenden sollte, könnt ihr diesen tollen StackOverflow Post lesen.
Wir werden nur die Grundlagen von NumPy lernen und es installieren, um damit arbeiten zu können.

<b>Sources</b><br>
[UdemyKursPythonFürFinanzanalysen](https://www.udemy.com/course/python-fur-finanzanalysen-und-algorithmisches-trading/learn/lecture/10014224#overview)

In [75]:
#!pip install numpy
import numpy as np

# Create DataStructure from Array

## Liste / Vektor / 1d

In [76]:
## hier erstelle ich einen NP-Vektor aus einer Python liste
myOwnList = [1,2,3] # => Liste
ownNpArray = np.array(myOwnList) 
ownNpArray
ownNpArray.dtype # => Ausgabe der inkludieten Datentypen

dtype('int32')

## Matrix / Tabelle / 2d

In [3]:
meine_matrix = [[1,2,3],[4,5,6],[7,8,9]] #=> mehrdimensionale Liste
meine_matrix
ownNpMatrix = np.array(myOwnList) 
ownNpMatrix.dtype # => Ausgabe der inkludieten Datentypen

dtype('int32')

In [4]:
meine_matrix = [[1,'Kai',3],[4,'Eva',6],[7,'Jochen',9]] #=> mehrdimensionale Liste
meine_matrix
ownNpMatrixWithCategorie = np.array(meine_matrix)
ownNpMatrixWithCategorie[:,0].dtype

dtype('<U11')

## create Array mit Numpy-Methoden / Sequenz

In [5]:
# Spanne über geiwissen bereich auf
print(np.arange(0,10)) # => array von 0(inkl) bis 10(exkl)
print(np.arange(0,20,2)) # => array von 0(inkl) bis 20(exkl) in 2 er schritten

[0 1 2 3 4 5 6 7 8 9]
[ 0  2  4  6  8 10 12 14 16 18]


## Zeros und Ones
Das kann besonders bei der Matritzen Rechnung von Bedeutung werden. Hier erstellen wir arrays mit ledilgich einzelnen werten


In [6]:
# Vektor mit nur 0
np.zeros(3)
# Matrix mit nur 0
np.zeros((5,5))
# nur 1er
np.ones(3)
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Linspace
Gleichverteilungen in angegebenem Raum

In [7]:
np.linspace(0,10,3) # Array
np.linspace(0,10,51)# Matrix

array([ 0. ,  0.2,  0.4,  0.6,  0.8,  1. ,  1.2,  1.4,  1.6,  1.8,  2. ,
        2.2,  2.4,  2.6,  2.8,  3. ,  3.2,  3.4,  3.6,  3.8,  4. ,  4.2,
        4.4,  4.6,  4.8,  5. ,  5.2,  5.4,  5.6,  5.8,  6. ,  6.2,  6.4,
        6.6,  6.8,  7. ,  7.2,  7.4,  7.6,  7.8,  8. ,  8.2,  8.4,  8.6,
        8.8,  9. ,  9.2,  9.4,  9.6,  9.8, 10. ])

## Eye-Fkt || Einheitsmatrix
erstellt eine Einheitsmatrix

In [8]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

## Symetrische Matrix via Loop

In [9]:
arr2d = np.zeros((10,10))
arr_laenge = arr2d.shape[1]
#print(arr2d)
for i in range(arr_laenge):
    arr2d[i] = i
    
arr2d
#print(arr2d)

# Subfunctions
arr2d[[2,4,6,8]]
arr2d[[6,4,8,2]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [10]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

# Numpy Basic-Functions

## Random
erstellt Random zahlen. Random return eine [Normalverteilung](https://github.com/JHC90/Basic-DataScience-Skills/wiki/Statistics_Basics_015_Normalverteilung)

In [11]:
np.random.rand(1)# Bereich zwischen 0 & 1 || 1 return value
np.random.rand(3)# Bereich zwischen 0 & 1 || 3 Return value
np.random.rand(5,5) # Random Matrix 5x5

array([[0.40503965, 0.97884958, 0.60046952, 0.51971358, 0.29457179],
       [0.64696347, 0.66219425, 0.60635301, 0.51110956, 0.70106166],
       [0.36724234, 0.30266803, 0.50908343, 0.88878061, 0.93669701],
       [0.83414774, 0.72975937, 0.11466106, 0.37555451, 0.7948572 ],
       [0.76364362, 0.38232391, 0.49289899, 0.06841042, 0.41594482]])

## randn
erstellt Random zahlen. randn return eine [StandardNormalverteilung](https://github.com/JHC90/Basic-DataScience-Skills/wiki/Statistics_Basics_015_Normalverteilung)

In [12]:
np.random.randn(500)
randMatrix = np.random.randn(3,3)
randMatrix

array([[-0.94768303,  0.14223653, -0.25651815],
       [-1.00613139,  0.65967935,  1.95387226],
       [ 0.87099683, -1.66270459,  0.41678781]])

## rand
erstellt Random zahlen. rand returnr eine [Gleichverteilung](https://github.com/JHC90/Basic-DataScience-Skills/wiki/Statistics_Basics_013_Gleichverteilung)

In [13]:
np.random.rand(5)
#np.random.rand(3,3)

array([0.78022043, 0.23984932, 0.9849156 , 0.03516776, 0.44718148])

## randint
Gibt Zufallszahlen von `low`(inklusive) bis `high`(exklusive) zurück.

In [14]:
np.random.randint(1,100) # => 1 ganzzahlige Zufallszahl zwischen 1 & 100
randArray = np.random.randint(1,100,10)# => 10 Zufallszahlen zwischen 1&100

## max, min, argmax, argmin

In [43]:
randArray

array([36,  8, 88, 17, 11, 83,  9, 54, 10, 24])

In [44]:
# Max-Value aus dem Randarray
randArray.max()
# index des Max-Value aus dem Randarray
randArray.argmax()
# Min-Value aus dem Randarray
randArray.min()
# index des Min-Value aus dem Randarray
randArray.argmin()

1

In [47]:
# Alternativen
np.max(randArray)
np.min(randArray)
np.argmax(randArray)
np.argmin(randArray)

1

# Reshape

In [17]:
# Data for Reshape-Section
arr = np.arange(30)

## Shape Function
mit der Shape function kann die gegenwärtige "Form des Arrays" abgefragt werden. Achtung das ist kein funktionsaufruf => keine "()" nach Aufruf des shape commands

In [18]:
randArray.shape
randMatrix.shape
randMatrix.shape[0] # =rows
randMatrix.shape[1] # =Columns

3

## Vektor => Matrix
hier wird ein Vektor zu einer Matrix umformuliert. D.h. es ist wichtig dass die Anzahl der elemente in dem Vektor gleich das Produkt aus Zeilen und Spalten aus der Matrix sind. Bsp 30 = 5*6 = 3*10 = 10*3 ......

In [19]:
arr.reshape(5,6) # Tranform in Matrix
arr.reshape(3,10)# Tranform in Matrix
arr.reshape(10,3)# Tranform in Matrix
arr.reshape(30,)# Tranform in Vektor = Flatten

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [20]:
arr.dtype

dtype('int32')

# Good to know bei Numpy für Select & Update Data || Slect vs Copy
Diesen Mult

## Ist-Situation
wenn ich aus einem gegebenen ORGINALARRAY ein SUBARRAY auswähle un dieses SUBARRAY ändere, so ändert sich auch der Wertebereich im eigentlichen ORGINALARRAY.

In [21]:
ORGINALARRAY = (np.arange(0,20,2))
print(ORGINALARRAY)
SUBARRAY = ORGINALARRAY[7:]
print(SUBARRAY)
SUBARRAY[:] = 100 # => alle werte in Subarray sind jetzt 100 UND im Orginalbereich hat sich auch der Wertebereich angepasst
print(SUBARRAY)
print(ORGINALARRAY)

[ 0  2  4  6  8 10 12 14 16 18]
[14 16 18]
[100 100 100]
[  0   2   4   6   8  10  12 100 100 100]


Anders ausgedrückt: Beim erstellen eines Subarrays muss man entscheiden ob man ein eigenständiges np.Array benötigt, oder sich immer wieder auf das eigentliche Array bezieht. 

## Lösung mit Copy

In [22]:
ORGINALARRAY = (np.arange(0,20,2))
ORGINALARRAY_Copied = ORGINALARRAY.copy()
SUBARRAY = ORGINALARRAY_Copied[7:]
SUBARRAY[:] = 100


print('##########---Hier nach der Modlifikaiton---##########')
print(ORGINALARRAY)
print(ORGINALARRAY_Copied)
print(SUBARRAY)


##########---Hier nach der Modlifikaiton---##########
[ 0  2  4  6  8 10 12 14 16 18]
[  0   2   4   6   8  10  12 100 100 100]
[100 100 100]


# Select Data

In [23]:
# Data for Selection-Demonstration
arr = (np.arange(0,20,2))
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

## 1D Vector

In [24]:
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### Single Value from Vector mit Index

In [25]:
arr[5]

10

### Wertebereich von Vector


In [26]:
arr[1:5] # untereGrenze = inkl // obere Grenze = exkl

array([2, 4, 6, 8])

### Auf Basis einer Bedingung || Filter Vector
hierzu arbeitet man mit den ablgelegten Boolean werten

In [27]:
# Bsp alle werte > 14
arr > 14
bool_arr = arr > 14
print(arr)
print(arr[bool_arr])

# Schneller Filter
print(arr[arr>17]) 

# Filter mit eingehender Variable
x=50
print(arr[arr>x])

[ 0  2  4  6  8 10 12 14 16 18]
[16 18]
[18]
[]


## 2d Matrix

In [28]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

### Reihe 

In [29]:
arr_2d[0]
arr_2d[1]
arr_2d[2,:] # Andere Schreibweise

array([35, 40, 45])

### Spalte
vgl Subsets

In [30]:
arr_2d[:,0]
arr_2d[:][1] # Alternative Schreibweise
#arr_2d[:,2]

array([20, 25, 30])

### Wert

In [31]:
arr_2d[1][0]

20

### Subset
Das Format ist arr_2d[row][col] oder arr_2d[row,col]

In [32]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

# Update Data
## Update Single-Value

In [33]:
arr[3] = 300490
arr

array([     0,      2,      4, 300490,      8,     10,     12,     14,
           16,     18])

## Broadcasting
mit dem Broadcasting können mehrere Werte in eienm Array zeitgleich upgedatet werden

In [34]:
arr[0:5]=100
arr

array([100, 100, 100, 100, 100,  10,  12,  14,  16,  18])

# Arithmetische Operationen am Numpy

## Addition von Array

In [35]:
arr2 = arr + arr
arr2

array([200, 200, 200, 200, 200,  20,  24,  28,  32,  36])

## Quadrieren von Array

In [36]:
arr3 = arr * arr
arr3

array([10000, 10000, 10000, 10000, 10000,   100,   144,   196,   256,
         324])

## Subtraktion von Array

In [37]:
arr4 = arr3 -arr2
arr4

array([9800, 9800, 9800, 9800, 9800,   80,  120,  168,  224,  288])

## Division von Array

In [38]:
arr5 = arr2 / arr
arr5 # 0> wurde zuvor ja mal 2 bzw arr +arr gerechnet => 2 ist somit logisch

array([2., 2., 2., 2., 2., 2., 2., 2., 2., 2.])

## Potenzieren von Array

In [39]:
arr6 = arr**2
print(arr6)
arr7 = arr**3
print(arr7)

[10000 10000 10000 10000 10000   100   144   196   256   324]
[1000000 1000000 1000000 1000000 1000000    1000    1728    2744    4096
    5832]


## Wurzel aus Array

In [50]:
# Data for sqrt
ownNpArray = np.array([9,16,25]) 

In [51]:
# Version1
arr8 = np.sqrt(ownNpArray) # => 
print(arr8) 
# Version2
arr9 = ownNpArray**0.5
print(arr9) 

[3. 4. 5.]
[3. 4. 5.]


## Calc Exponenten e

In [52]:
np.exp(ownNpArray)

array([8.10308393e+03, 8.88611052e+06, 7.20048993e+10])

## Log

In [66]:
np.log(ownNpArray)

array([2.19722458, 2.77258872, 3.21887582])

## Demo e und Log

In [65]:
print(ownNpArray)

expOwnNPArray = np.exp(ownNpArray)
print(expOwnNPArray)

logExpOwnNPArray = np.log(expOwnNPArray)
print(logExpOwnNPArray)

[ 9 16 25]
[8.10308393e+03 8.88611052e+06 7.20048993e+10]
[ 9. 16. 25.]


## Sinus

In [57]:
np.sin(arr)

array([-0.50636564, -0.50636564, -0.50636564, -0.50636564, -0.50636564,
       -0.54402111, -0.53657292,  0.99060736, -0.28790332, -0.75098725])

## Cosinus

In [58]:
np.cos(arr)

array([ 0.86231887,  0.86231887,  0.86231887,  0.86231887,  0.86231887,
       -0.83907153,  0.84385396,  0.13673722, -0.95765948,  0.66031671])

## Tangens

In [59]:
np.tan(arr)

array([-0.58721392, -0.58721392, -0.58721392, -0.58721392, -0.58721392,
        0.64836083, -0.63585993,  7.24460662,  0.30063224, -1.13731371])

## Matrix

In [70]:
arr = np.arange(1,26)
matrix = arr.reshape(5,5)
matrix

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

### Spaltensumme

In [71]:
print(sum(matrix))

[55 60 65 70 75]


### Matrixsumme

In [72]:
print(sum(sum(matrix)))

325


### Standardabweichung Matrix

In [79]:
np.std(matrix)

7.211102550927978

### Varianz Matrix

In [78]:
np.var(matrix)

52.0